#server
server:
  port: 8488

#database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschool?characterEncoding=utf8
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml

resource:
  id: fy-school

security:
  oauth2:
    resource:
      filter-order: 3