-- MySQL Script generated by MySQL Workbench
-- 05/12/18 20:28:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myschool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myschool` DEFAULT CHARACTER SET utf8mb4 ;
USE `myschool` ;

-- -----------------------------------------------------
-- Table `myschool`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`user` (
  `id` BIGINT(20) NOT NULL COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `username` VARCHAR(128) NOT NULL COMMENT '',
  `password` VARCHAR(128) NOT NULL COMMENT '',
  `salt` VARCHAR(32) NOT NULL COMMENT '',
  `title` VARCHAR(32) NULL COMMENT '',
  `phone` VARCHAR(11) NOT NULL COMMENT '',
  `address` VARCHAR(32) NULL COMMENT '',
  `last_login_time` TIMESTAMP(14) NULL COMMENT '',
  `login_count` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myschool`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`role` (
  `id` BIGINT(20) NOT NULL COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `name` VARCHAR(32) NOT NULL COMMENT '',
  `type` INT NOT NULL COMMENT '',
  `parent_id` BIGINT(16) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myschool`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `menu` VARCHAR(45) NOT NULL COMMENT '',
  `operation` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myschool`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`user_role` (
  `id` BIGINT(20) NOT NULL COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `user_id` BIGINT(20) NOT NULL COMMENT '',
  `role_id` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myschool`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`role_permission` (
  `id` BIGINT(20) NOT NULL COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `role_id` BIGINT(20) NOT NULL COMMENT '',
  `permission_id` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myschool`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myschool`.`student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `create_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP(14) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `birthday` TIMESTAMP(14) NOT NULL COMMENT '',
  `age` INT NULL COMMENT '',
  `sex` TINYINT(1) NOT NULL COMMENT '',
  `parent` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
